export { ThreeGradientBackground } from "./ThreeGradientBackground";
export type { ThreeGradientBackgroundProps, NoiseType } from "./ThreeGradientBackground";
export { GradientControls } from "./GradientControls";
export type { GradientControlsProps } from "./GradientControls";
export { ThreeBGProvider, useThreeBG } from "./ThreeBGContext";
export type { ThreeBGControls, ThreeBGProviderProps, ThreeBGState } from "./ThreeBGContext";
export { DEFAULT_PRESET, DARK_PRESET, LIGHT_PRESET } from "./presets";
export type { GradientPreset } from "./presets";
export { DITHER_TYPES } from "./shaders/ditherShader";
export type { DitherType } from "./shaders/ditherShader";
