import { InfrastructureNode } from './types';

export const INITIAL_NODES: InfrastructureNode[] = [
    // WATER
    {
        id: 'irrigation',
        name: 'Irrigation Canals',
        category: 'WATER',
        parentId: null,
        startYear: -4000,
        endYear: 1900,
        peakYear: -1000,
        description: 'Early water management systems for agriculture in Mesopotamia and Egypt.',
        magnitude: 3,
    },
    {
        id: 'aqueducts',
        name: 'Aqueducts',
        category: 'WATER',
        parentId: 'irrigation',
        startYear: -312,
        endYear: 500,
        peakYear: 100,
        description: 'Roman engineering marvels for transporting water over long distances.',
        magnitude: 5,
    },
    {
        id: 'modern-plumbing',
        name: 'Modern Plumbing',
        category: 'WATER',
        parentId: 'aqueducts',
        startYear: 1800,
        endYear: 2050,
        peakYear: 1950,
        description: 'Pressurized water and sewage systems for urbanization.',
        magnitude: 8,
    },

    // TRANSPORT
    {
        id: 'roads-trackways',
        name: 'Ancient Trackways',
        category: 'TRANSPORT',
        parentId: null,
        startYear: -4000,
        endYear: -300,
        peakYear: -1000,
        description: 'Simple cleared paths for walking and livestock.',
        magnitude: 2,
    },
    {
        id: 'roman-roads',
        name: 'Roman Roads',
        category: 'TRANSPORT',
        parentId: 'roads-trackways',
        startYear: -300,
        endYear: 400,
        peakYear: 100,
        description: 'Paved road networks connecting the empire.',
        magnitude: 6,
    },
    {
        id: 'canals-transport',
        name: 'Transport Canals',
        category: 'TRANSPORT',
        parentId: null,
        startYear: 1600,
        endYear: 1900,
        peakYear: 1800,
        description: 'Artificial waterways for heavy cargo transport.',
        magnitude: 5,
    },
    {
        id: 'railways',
        name: 'Railways',
        category: 'TRANSPORT',
        parentId: 'canals-transport', // Competing/Evolving from canals
        startYear: 1825,
        endYear: 2050,
        peakYear: 1920,
        description: 'Steam and later electric trains revolutionizing land transport.',
        magnitude: 9,
    },
    {
        id: 'highways',
        name: 'Interstate Highways',
        category: 'TRANSPORT',
        parentId: 'roman-roads', // Conceptual successor
        startYear: 1930,
        endYear: 2050,
        peakYear: 2000,
        description: 'High-speed automotive networks.',
        magnitude: 10,
    },

    // ENERGY
    {
        id: 'water-wheels',
        name: 'Water Wheels',
        category: 'ENERGY',
        parentId: null,
        startYear: -200,
        endYear: 1800,
        peakYear: 1400,
        description: 'Mechanical energy from flowing water.',
        magnitude: 4,
    },
    {
        id: 'steam-engine',
        name: 'Steam Power',
        category: 'ENERGY',
        parentId: 'water-wheels',
        startYear: 1712,
        endYear: 1950,
        peakYear: 1900,
        description: 'Industrial scale power generation.',
        magnitude: 8,
    },
    {
        id: 'electric-grid',
        name: 'Electric Grid',
        category: 'ENERGY',
        parentId: 'steam-engine',
        startYear: 1880,
        endYear: 2050,
        peakYear: 2020,
        description: 'Distribution of electricity to homes and industry.',
        magnitude: 10,
    },

    // DIGITAL
    {
        id: 'telegraph',
        name: 'Telegraph',
        category: 'DIGITAL',
        parentId: null,
        startYear: 1837,
        endYear: 1950,
        peakYear: 1900,
        description: 'Long-distance instantaneous communication.',
        magnitude: 5,
    },
    {
        id: 'telephone',
        name: 'Telephone Network',
        category: 'DIGITAL',
        parentId: 'telegraph',
        startYear: 1876,
        endYear: 2050,
        peakYear: 2000,
        description: 'Voice communication infrastructure.',
        magnitude: 8,
    },
    {
        id: 'internet',
        name: 'Internet Backbone',
        category: 'DIGITAL',
        parentId: 'telephone',
        startYear: 1969,
        endYear: 2050,
        peakYear: 2024,
        description: 'Global packet-switching network.',
        magnitude: 10,
    },
    {
        id: 'source-infrastructure',
        name: 'SOURCE',
        category: 'DIGITAL', // Or a new custom category if needed, but Digital fits well
        parentId: 'internet',
        startYear: 2024,
        endYear: 2044, // 20 years into future
        peakYear: 2040,
        description: 'Infrastructure for super awareness and effective superintelligence.',
        magnitude: 10,
    },
];
